### ISSUE TITLE
Tested plugin with SDK v6 and it works

### ISSUE THREAD

**Issue by nleclerc** [mattrayner/cordova-plugin-vuforia#101]
Just for info :-D

**Comment by mattrayner** [comment]
I'll be doing a migration really soon :)

**Comment by mattrayner** [comment]
I'm planning on reading the EULA for this over the next couple of days - I want to make sure we don't fall foul of anything in there

**Comment by mattrayner** [comment]
@dsgriffin think you could try to update the SDK to 6.0 whilst I read through this? #103 means we don't really have a choice with the upgrade anyways

**Comment by dsgriffin** [comment]
The SDK has now been updated to v6.0.117, just need it pushed to npm and then we can update the dependencies of this package and push it live

**Comment by mattrayner** [comment]
3.2.1 has now been released - I'm just waiting for #106 to be merged into master
