### ISSUE TITLE
Memory Leak in iOS 

### ISSUE THREAD

**Issue by ryanchanplc** [mattrayner/cordova-plugin-vuforia#102]
hi , 

i use this plugin with cordova-vuforia-example in ionic framework.

https://github.com/dsgriffin/cordova-vuforia-example

when i stop and restart vuforia in the ionic, the memory allocated is keep increasing , there might be a memory leak. Please help.

Thanks

**Comment by mattrayner** [comment]
Hi Ryan,
 Do you have some sample code you can show me?

**Comment by ryanchanplc** [comment]
Hi Matt

I didnt add any native codes.I just create a new ionic project , and add this plugin. 
Simply I created a button to trigger startVuforia in index.html according to your guide.

However , i think the leak may original coming from vuforia itself. Because i found that vuforia's official native iOS sample has memory leak by tracing inside **Instrument**.

**Comment by ryanchanplc** [comment]
The dealloc in both ImageTargetsViewController and ImageTargetsEAGLView are not called.

After adding `self.imageRecViewController=nil;` inside **VP_closeView** in VuforiaPlugin.m may help.

```
- (void) VP_closeView {
    if(self.startedVuforia == true){
        [self.imageRecViewController close];
        self.imageRecViewController=nil;
        self.startedVuforia = false;
    }
}
```

**Comment by mattrayner** [comment]
I'll take a look into this over the next few days and get a fix implemented and in place

**Comment by mattrayner** [comment]
Hi @ryanchanplc, I've added the line you suggested in, but it doesn't look to have changed much - I think the cause of this issue may be within the Vuforia library - in my testing it looks like the base memory amount does increase with every launch, but in our example app it doesn't seem to be a huge jump. Hopefully any underlying issues will be ironed out in the next few releases of Vuforia and we will see the benefits
