### ISSUE TITLE
Google Play will block the update and publication of Android apps that use vulnerable versions of libpng

### ISSUE THREAD

**Issue by AppwareDev** [mattrayner/cordova-plugin-vuforia#103]
From Vuforia:

Effective September 17, 2016, Google Play will block the update and publication of Android apps that use vulnerable versions of libpng, a software library that enables the loading/saving of PNG images. Even though Vuforia does not expose this vulnerability with its use of libpng, an update to your app will still be required. More details on the libpng vulnerability are available at Google Support.

In order to prevent your submission from being blocked by Google Play you must update your Vuforia app with SDK version 6.0.117 or later. If you’ve already published an app with Vuforia it will remain live in the Google Play store, but a Vuforia update is required the next time you submit it.

To get started, download the updated Vuforia SDK for Android or Unity Extension. If you are using Vuforia 5 or earlier, you can refer to the upgrade guide. The Vuforia Unity sample apps will be updated soon.

[Source](http://app.demand.ptc.com/e/es.aspx?s=2826&e=756530&elqTrackId=c346145430f045a9a4a8ab0ad69df3d1&src=View_Online&elq=96cacb492fbf4856a723bbd79d1d7cfa&elqaid=19815&elqat=1)

**Comment by mattrayner** [comment]
Thanks for letting me know, I'll be sure to update to 6.0 ASAP

**Comment by mattrayner** [comment]
As per #101 we're beginning the upgrade now
