### ISSUE TITLE
Display html after image recognition

### ISSUE THREAD

**Issue by danyarzeta** [mattrayner/cordova-plugin-vuforia#104]
​
## Expected Behavior
Is there any way to display an html on the image when it is recognized?

​
## Current Behavior
Every time vuforia recognized an image it gets closed. I don't need that the camera gets closed, i want it to display an html even when the camera is on, with out closing vuforia.

​
## Possible Solution
Instead of displaying a media sound, i want to display an html.

​
## Context

​
## Your Environment

* Cordova version used: 6.3.1
* Plugin version used: 3.2.0
* Plaforms affected: iOS / Android
* iOS/Android versions affected:

**Comment by dsgriffin** [comment]
> Every time vuforia recognized an image it gets closed. I don't need that the camera gets closed

Check out the `autostopOnImageFound` option mentioned in the README if you'd like to keep the camera open upon recognition. 

> i want it to display an html even when the camera is on

The answer to this is the same as #86 and #87 I believe - that you'll need to write some native device-specific code yourself as this is very customised behaviour and not in the scope of this plugin.
