### ISSUE TITLE
Adding tracking data (pose) to the plugin to allow 3d models to track to the Vuforia target

### ISSUE THREAD

**Issue by Flikker** [mattrayner/cordova-plugin-vuforia#109]
​
## Expected Behavior

Having read issues #86 and #87 (similar questions but not exactly the same), this may not be possible, but it would be great to extend the plugin to be able to use tracking info (pose) rather than just registering when a target has been detected, so that I could enable three.js to add 3d models over images and Vumarks.
Although elements such as adding transparent webviews (if indeed that's the best way to go?) and passing tracking data to three.js are almost certainly outside the scope of this plugin, things such as adding the tracking data to the plugin are part of Vuforia image recognition.

​
## Possible Solution

I'm not very experienced but I'm happy to have a go at doing this if no-one else has the time/inclination; but I'd really appreciate if someone could give me a few pointers on how to tackle it, to check I'm on the right track! I'm thinking:
- add the Java tracking elements from the Vuforia SDK into the current cordova plugin
- once Vuforia has detected a target, begin tracking, and also start three.js in a transparent Crosswalk webview above the camera
- pass the tracking info from Vuforia in the camera activity to the transparent Crosswalk webview above it and allow three.js to put a 3d model above the Vuforia target.

Thanks!
​

**Comment by mattrayner** [comment]
Hi Flikker,
 Thanks very much for taking the time to create this issue :) unfortunately this isn't possible with the current plugin - how it works at the moment is:

- Cordova triggers the plugin
- A new ViewController is created and launched
  - This view controller uses the native Vuforia SDK to monitor for targets
  - The user find a target, or triggers a close
- The ViewController returns an object back to cordova

All of the indented points are effectively seperate and andboxed from the cordova part of your application. Launching the plugin effectively opens a mini-vuforia app of it's own. You're able to send messages in via a simple interface, then you just wait for a response. Unfortunately the vuforia side of your application is very opaque - there's no way to add elements on top using the cordova environment, this is why any additional rendering etc has to be done on a system-by-system basis.

For example, i'm not 100% on how I would pass an image from Cordova through the sandbox and into the Vuforia ViewController that could then be displayed, or a video for that matter.

I'm sorry this probably wasn't the answer you hoped for - you could always take my plugin and extend it to allow some more specific behaviors on the Vuforia side?
