### ISSUE TITLE
Play video on target image

### ISSUE THREAD

**Issue by baquy96** [mattrayner/cordova-plugin-vuforia#110]
Hi mattrayner,
I want to play video on image target when camera found it.
It's easy to do with Unity.
But I don't know how to do it on Cordova.

**Comment by mattrayner** [comment]
Hi @baquy96,
 Sorry for the delay in replying, your issue slipped through my net!

The issue with playing a video within the camera view is that my version has largely been created to cater for image recognition only. Adding video playback would need to be done per-device and is out of scope of the current plugin.

If this is something you're interested in working on, I'd love to offer you any help you needed and would happily accept a pull request 🙂
