### ISSUE TITLE
Problem building in production

### ISSUE THREAD

**Issue by linuxs** [mattrayner/cordova-plugin-vuforia#111]
​
## Expected Behavior
Successful build on Xcode with plugin installed in project. 
​
## Current Behavior

Building with Ionic produces an error with Xcode and will not compile.
​
## Possible Solution

​
## Steps to Reproduce (for bugs)

1. Integrate in Ionic project
2. Build with Ionic build ios 

## Context

I am unable to use the plugin due to these compile errors.
​
## Your Environment

* Cordova version used: 6.0.0
* Plugin version used: Latest (3.2.0 I believe)
* Plaforms affected: iOS / Android (Both)
* iOS/Android versions affected:

**Comment by linuxs** [comment]
Resolved this. Basically you cant build for a simulator.

**Comment by dsgriffin** [comment]
@linuxs Apologies for the lack of reply. Glad you resolved your issue
