### ISSUE TITLE
Vuforia for cordova app

### ISSUE THREAD

**Issue by AgNm** [mattrayner/cordova-plugin-vuforia#113]
​
## Expected Behavior
I have created a sample cordova app. I have also created a sample android app. In Android, I can see below image: http://1.bp.blogspot.com/-ucDjcZHfrpE/T0EpVv7nwqI/AAAAAAAAA84/nYa7KzZJj34/s1600/desireRA.jpg

But it is not working same for cordova app.

How I can make it work for cordova app same as native android app?
​
## Your Environment
* Cordova version used: 6.5.0
* Plugin version used:  3.2.1
* Plaforms affected: iOS / Android

**Comment by mattrayner** [comment]
Hi AnG,
 The android screen shot you've include - is that using the plugin or the native Vuforia samples?

**Comment by AgNm** [comment]
Hi @mattrayner,

It is using native Vuforia samples. But I want to do same in Cordova Apps.

**Comment by AgNm** [comment]
@mattrayner Can you please suggest on this, how I can proceed to make it work same as native.

**Comment by mattrayner** [comment]
Hi AnG,
 At the moment this plugin uses Vuforia for image recognition only. Going forward I may investigate using it for augmented reality but this is currently out of scope.

Thanks,
Matt

**Comment by AgNm** [comment]
@mattrayner Thanks, I'm waiting for same.
