### ISSUE TITLE
Add custom text and image overlay on the camera view

### ISSUE THREAD

**Issue by fariskas** [mattrayner/cordova-plugin-vuforia#116]
Hi, not a bug but rather a question.

Currently in the camera view, i see that there is a  'overlayMessage' which is editable and the vuforia logo.

How can i add my own images and own text with custom positioning to the camera view?
I'm looking to add an everpresent grid / guides overlay. 

Currently using it only for IOS with cordova. Thanks

**Comment by mattrayner** [comment]
Hi @fariskas, at the moment you'd need to modify the code inside of the plugin's view controller to achieve what you're asking

It should be pretty simple though! 👍

**Comment by fariskas** [comment]
thanks for the quick reply. could you point me to the files you were referring to perhaps?
