### ISSUE TITLE
Path problem for the .xml file?

### ISSUE THREAD

**Issue by Stending** [mattrayner/cordova-plugin-vuforia#15]
Hi, I've been experiencing many problem with the reading of the xml database file when calling the startVuforia() method, and I think there is an issue.
It doesn't work with the StoneAndChips.xml sample, and I don't know where to add my own xml file.

Thank you!

**Comment by mattrayner** [comment]
Hi Mattheiu,
 When you say you're experiencing issues, what exactly do you mean?

Is there an error message you can give me or any more information?

Thanks,
Matt

**Comment by robersant** [comment]
Hi, how're you? I've a similar problem, but only when I try to add my own Vuforia Database. The StoneAndChips.xml works perfect, but when I try to use my own XML the plugin returns the error "Failed to load tracker data". Im locating my XML in the same folder that is StoneAndChips.xml, and i've tried with two different XMLs, but the only one that works is StoneAndChips.xml. Can be? Thanks!!

**Comment by mattrayner** [comment]
@robersant I saw you created a comment then it was gone - did you find a solution to your issue?

**Comment by robersant** [comment]
​
Hi Matt! Yes, i found the solution just in time: i've to update the
plugin.xml too, replacing the name of the resources (DAT and XML file).

[image: Inline image 2]

Thanks anyway!

**Comment by mattrayner** [comment]
Hi @robersant & @Stending,
 So that nothing breaks if you update the `cordova-plugin-vuforia` plugin we recommend that you reference your data and XML files from you app's `config.xml` file like so:

```xml
<platform name="android">
    <resource-file src="targets/CustomData.dat" target="assets/CustomData.dat" />
    <resource-file src="targets/CustomData.xml" target="assets/CustomData.xml" />
</platform>

<platform name="ios">
    <resource-file src="targets/CustomData.dat" target-dir="com.bdnetwork.vuforia" />
    <resource-file src="targets/CustomData.xml" target-dir="com.bdnetwork.vuforia" />
</platform>
```

In the root of your projects you shouyld create a `targets` directory containing your two files.

We'll update the [README](README.md) to include this information

**Comment by mattrayner** [comment]
We'll look at updating the README file to include the above instructions

**Comment by Stending** [comment]
Well, the .xml file isn't loaded. And your exemple with StoneAndChips.xml
doesn't work too..

I have no special error, but if you go down in the Objectice-C, you can
find an error about file reading. (Can't show you which now).
I also tried to test if the file received in the startVuforia method exist,
and no matter where I put the file, it says that it doesn't exist..

Thank you.

**Comment by mattrayner** [comment]
What version of cordova-ios are you using? The latest version (4.1.*) has some differnet setup instructions - we updated our README with some information that might help?

**Comment by dsgriffin** [comment]
Hi @Stending, there's an example project here: https://github.com/dsgriffin/cordova-vuforia-example. Does this example project work for you?

**Comment by mattrayner** [comment]
Hi @Stending, did you get anywhere with this?

**Comment by Stending** [comment]
I didn't have the time to continue testing, I'll be able to check all this
friday!
And I use Cordova ios 4.1.1, so maybe this is the problem.

Thank you for your fast answers, i'll keep you informed!

**Comment by mattrayner** [comment]
Thanks for letting us know, we've never actually tested this on 4 😞  

If it's a small issue I cant see any reason we shouldn't be able to work out a fix **Famous Final Words**

Let us know how you get on 👍

**Comment by Stending** [comment]
Okay so, I managed to make the StoneAndChips example work, that was just a mistake of mine, but I'm still not able to use my own database.

I included the .xml and .dat in a targets folder in the root, and added them in my config.xml file just like you said to, but it just doesn't work.
When I look at the assets files for android, I just see the StonesAndChips files added by the plugin.xml, but my config.xml does nothing...

I'm not sure we can use <resource-file> in a config.xml by the way...

I'll continue testing, thanks again for helping me so quickly!

**Comment by mattrayner** [comment]
Update: We are currently testing this - once we have a working solution we'll update you all 👍

**Comment by dsgriffin** [comment]
@Stending @remib Hey, we're just about to update the docs to show how to use custom data files by including a `targets/` folder inside `www/` & changing some paths - here's a working example: https://github.com/dsgriffin/cordova-vuforia-example

**Comment by remib** [comment]
Excellent! Perfect timing as we're looking to release in the next few days. Thanks guys.

**Comment by mattrayner** [comment]
Let us know if you have any more issues and we'll re-open
