### ISSUE TITLE
Cordova iOS 4.* orientation locking issue

### ISSUE THREAD

**Issue by mattrayner** [mattrayner/cordova-plugin-vuforia#16]
The recent update to `cordova-ios@4.*` breaks our previous orientation locking code and advice. We should try and find a solution that allows for reliable orientation locking in iOS

**Comment by mattrayner** [comment]
Appears to be related to this:

**Comment by nleclerc** [comment]
Orientation issues have been resolved in this PR : https://github.com/mattrayner/cordova-plugin-vuforia/pull/84

Behavior now is the vuforia scanner will mimic accept the same orientations as its parent view (ie. the cordova view controller).
