### ISSUE TITLE
Overlay devices icon

### ISSUE THREAD

**Issue by Stending** [mattrayner/cordova-plugin-vuforia#49]
Hi!
I'm trying to improve a bit the vuforia overlay, by making it a bit customizable (now that we have an options object, we can add many optionals parameters).
Do you need to keep the devices icon? It doesn't look essential, and doesn't fit well with what I'm doing.

Thank you!

**Comment by mattrayner** [comment]
The devices icon is kind of an artefact... It was added as a 'scan a page with this icon on it' kind of thing

It's not essential, but just removing it wholesale seems a bit permanent... We could make an options flag that allows it to not be added to the screen?

**Comment by Stending** [comment]
Okay, now the devices icon is optional, and disabled by default! I have some changes to do, I'll do my pull request soon.
Thank you!
