### ISSUE TITLE
Status bar doesn't show on landscape mode on iOS

### ISSUE THREAD

**Issue by Stending** [mattrayner/cordova-plugin-vuforia#51]
Hi,
On an Ipod touch, when vuforia is running, the status bar is showing in portrait mode, but not in landscape.
It looks like this is a common problem with the view controllers.

Ideally, we need to fix the bug to show the status bar on landscape mode, and why not make an option to hide or not the status bar on the vuforia plugin.

On my side, I'm actually hiding the bar on the vuforia plugin, we don't really need it.
That can be a temporary solution, I can immediately make a pull request if you want.

Thank you!

**Comment by mattrayner** [comment]
If you could create a PR that would be great - for now I'd rather have consistent behaviour - we can look at making this a config flag in the future :+1:
