### ISSUE TITLE
Renaming `dismiss` to `stopVuforia`

### ISSUE THREAD

**Issue by mattrayner** [mattrayner/cordova-plugin-vuforia#56]
​
## Expected Behavior
If the user calls `startVuforia(...);` to begin a Vuforia session, should they call `stopVuforia();` to end it?
​
## Current Behavior
The user current has to call `startVuforia(...);` to begin and `dismiss();` to end it.
​
## Possible Solution
Rename `dismiss` to `stopVuforia`.
​
## Context
This just seems a little strange and inconsistent. It would be nice if the method names were consistent.

**Comment by mattrayner** [comment]
What do you all think? @dsgriffin @nleclerc @Stending

**Comment by dsgriffin** [comment]
Sounds good to me 👍 could be added to #57

**Comment by mattrayner** [comment]
That's a good shout...

**Comment by nleclerc** [comment]
If we're renaming things why not go for just `start` ?
It's `navigator.VuforiaPlugin.startVuforia` after all, a bit redundant if you ask me.
We could then have `start` and `stop`.
What do you say ?

**Comment by mattrayner** [comment]
@nleclerc I agree with what you're saying for sure, maybe `start` and `stop` lack some context?

`startSession` and `stopSession` night be better?

I just feel a bit like 'what am I starting?` with `start`

I'll take it to a vote though? @dsgriffin @Stending

**Comment by mattrayner** [comment]
Intact, on reflection, I think I agree with start and stop. I'm thinking ahead to potential future improvements, rather than what's best for now.

I'll happily do `start` and `stop`, this will, however, make this a 3.0.0 change rather than 2.1.0 (`startVuforia` -> `start`) would be a breaking change.

For now should we do `stopVuforia` so it's consistent and open a new issue?

**Comment by dsgriffin** [comment]
@mattrayner sounds good to me - 3.0 will involve quite a few changes anyway so one more won't hurt.

**Comment by nleclerc** [comment]
Why not `startScanner` and `stopScanner` ?

**Comment by mattrayner** [comment]
@nleclerc Oooh, I like `startScan` & `stopScan` 👍
