### ISSUE TITLE
show an overlayed player on the image

### ISSUE THREAD

**Issue by vahidreza** [mattrayner/cordova-plugin-vuforia#87]
hi @mattrayner 
i have a scenario in which i need to show an overlay video player on the image and allow the user to play/pause the video. I may need some other video controls like turning on flash or focus and so on.
is it possible in phonegap with this plugin?

by the way how can i add my own overlay image watermark to the camera?

**Comment by mattrayner** [comment]
At the moment, this plugin does not support overlaying video.

This is completely do-able, but it will require some native device-specific code to complete.

The overlay image will also need to be implemented using native code on a per-platform basis
